#!/bin/bash

filename="logmein.py"
install_location="/usr/bin/logmein"
credential_file=~/.login.txt

#Uninstall option
if test "$1" == "--uninstall"
then
    echo "About to uninstall LogMeIn"
    echo "Are you sure ? <Y/n>"
    read sure
    if test sure == 'Y'
    then
        sudo rm -f "$install_location"
        exit 0
    fi
fi

#Copy file
sudo cp -f  $filename $install_location

#Setup Credential
echo -n "Do you want to setup you wifi credential file <y/n>? "
read sure
if test $sure == 'y'
then
    echo -n 'Enter your wifi username: '
    read username
    echo -n 'Enter your wifi password: '
    read password

    echo -e "$username\n$password" > $credential_file
    echo "Saved to $credential_file"
fi

